### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IalsaSynthesis#18]
(_Spun off from https://github.com/IALSA/Diabetes-Tri-Study/issues/1_)

@andkov, do you have a plan for excluding them systematically & clearly?  If there's a clear variable that explains why they should be dropped, do that programmatically (eg, a DOB before 1920)

If not, I suggest creating a "blacklist" called something like `exclude_manual.csv` or `blacklist.csv`.  There's a row for every subject/observation/whatever that you want to drop with a _manual_ specification.  Typically I'll add a second column called something like `exclude` which is usually TRUE for most the rows, but it allows me to stop excluding them, while not deleting the record (and potnetially losing the ID values I was suspicious of).  I'll also add a third column called `notes` that explains to outsiders why I didn't think they were a representative part of the sample.

Do you think many studies will have the need for this?  If so, we might include some common functions in this package.

**Comment by andkov** [comment]
Great idea, @wibeasley. I'm on it. Yes, I'd say that the each study should have this option

**Comment by smhofer** [comment]
You home?

On Jul 24, 2015, at 8:28 PM, Andrey Koval <notifications@github.com<mailto:notifications@github.com>> wrote:

Great idea, @wibeasleyhttps://github.com/wibeasley. I'm on it. Yes, I'd say that the each study should have this option

##

**Comment by ialsa-lab** [comment]
Just arrived to Toronto!

Sent from my iPhone, please excuse typing and T9 errors.

On Jul 24, 2015, at 3:41 PM, Scott Hofer <notifications@github.com<mailto:notifications@github.com>> wrote:

You home?

On Jul 24, 2015, at 8:28 PM, Andrey Koval <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:

Great idea, @wibeasleyhttps://github.com/wibeasley. I'm on it. Yes, I'd say that the each study should have this option

## 

Reply to this email directly or view it on GitHubhttps://github.com/IALSA/IalsaSynthesis/issues/18#issuecomment-124657548.

##
