### ISSUE TITLE
GitHub for package

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IalsaSynthesis#2]
@andkov, will you please 
- [x] See if you like the name `IalsaSynthesis` for this package?
- [x] Assuming so, create a team called `IalsaSynthesisPushPull`
- [x] Populate it with the people you want to have write privileges (of course this can be added to later).
- [x] Tell me their _public_ email addresses.  This will be posted on CRAN.

**Comment by andkov** [comment]
@wibeasley my public email address is andkov@uvic.ca
At this point, i don't see who else we need to invite to @IALSA/ialsasynthesispushpull
