### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by wibeasley** [IALSA/IalsaSynthesis#5]
https://coveralls.io/ integrates with Travis-CI to determine how much of the functions are covered by tests.
- [x] @andkov, can you please go to https://coveralls.io/ and turn on permissions for this repository?  It's not giving me the options.  I'm guessing it's because I'm not an admin of IALSA's GitHub "organization".
- [x] after that, I'll follow the rest of the instructions in https://github.com/jimhester/covr

**Comment by andkov** [comment]
permission added to IALSA / IALSA-2015-Portland and  IALSA / IalsaSynthesis repositories

**Comment by wibeasley** [comment]
Thanks, but it's still not visible to Coveralls.  I see the change in GitHub though.  I've re-synced it a few times. Do you mind see if you can turn it on?  There's been some bugs with it before, and I'm wondering if this is one of them.

**Comment by andkov** [comment]
I've turned on permissions, but it still asks me to "set up coveralls" 

SET UP COVERALLS
Here's some quick setup instructions for Ruby and Travis CI:
First, if you are using Travis CI , make sure it's building correctly. If you're using Travis Pro, add the following lines to a .coveralls.yml file in your repository's root:
service_name: travis-pro
repo_token: xxxxx
If you intend to submit coverage data via a private CI or command line other than Travis Pro, add the following line to your .coveralls.yml :
repo_token: xxxxxx
Note: Do not make your repo token public.
Add our gem to your Gemfile:
gem 'coveralls', require: false
In your spec_helper.rb or test_helper.rb or what have you:
require 'coveralls'
Coveralls.wear!

# Your code here.

And that's that! Coverage for your next Travis build should appear here!

**Comment by andkov** [comment]
@wibeasley, I've added you to the owners to IALSA organization

**Comment by wibeasley** [comment]
Done: https://coveralls.io/r/IALSA/IalsaSynthesis

It's because my membership in the IALSA organization wasn't public. Coveralls worked for me once it was.  See #8

**Comment by wibeasley** [comment]
I'm sorry @andkov, we forgot to save time for your question about coveralls.  It basically reports how much of the package's function code is tested.  A package with only a few tests has a low coverage percentage (say 10%).  Ideally, the coverage is 100%.  This simple metric can be misleading, but it's a good start.

This shows how the coverage has changed across builds/commits: https://coveralls.io/r/IALSA/IalsaSynthesis

This shows which functions are covered within a single build/commit: https://coveralls.io/builds/2460348

Once the config files are created, it run automatically anytime Travis-CI runs (which in turn runs automatically anytime code is committed to GitHub).

**Comment by andkov** [comment]
thanks, @wibeasley, it makes much more sense now.
